version: 2

references:
  workspace_root: &workspace_root
    ./

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root


jobs:
  build:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv

    steps:
      - checkout
      - run: npm install
      - run: npm install polymer-cli
      - run: npm run build
  
  publish: 
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv
    
    steps:
      - *attach_workspace
      - run: npm run frau:publish
    
  release:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv
    
    steps:
      - *attach_workspace
      - run: npm run frau:release

workflows:
  version: 2

  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
  
  release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - /^release.*/