version: 2

jobs:
  build:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv

    steps:
      - checkout
      - run: curl -sSf -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/npm-local/auth/d2l" -o .npmrc
      - run: curl -sSf -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/attest/auth/attest" >> .npmrc
      - run: npm run install-attest
      - run: npm install
      - run: npm install polymer-cli
      - run: npm run lint
      - run: npm run test:polymer:sauce
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths: .

  publish:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "export DEV_VER=$CIRCLE_SHA1" >> $BASH_ENV
      - run:
          name: frau:publish
          command: |
            npm run frau:build-config
            npm run frau:publish
  release:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "export PACKAGE_VER=$(node scripts/package-version.js)" >> $BASH_ENV
      - run:
          name: frau:release
          command: |
            npm run frau:build-config
            npm run frau:release

workflows:
  version: 2

  build-and-publish-or-release:
    jobs:
      - build:
          context: ci-read
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /^release.*/
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - /^release.*/
