version: 2

jobs:
  build:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv

    steps:
      - checkout
      - run: curl -sSf -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/npm-local/auth/d2l" -o .npmrc
      - run: npm install
      - run: npm install polymer-cli
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths: .

  publish:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv

    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run frau:publish

  release:
    docker:
      - image: dmoscrop/circleci-node8.10-tfenv

    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run frau:release

workflows:
  version: 2

  build-and-publish-or-release:
    jobs:
      - build:
          context: ci-read
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /^release.*/
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - /^release.*/
