name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          curl -sSf -u${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASS }} "https://d2lartifacts.jfrog.io/d2lartifacts/api/npm/npm-local/auth/d2l" -o .npmrc
          npm install
          curl -sSf -u${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASS }} "https://d2lartifacts.jfrog.io/d2lartifacts/api/npm/attest/auth/attest" >> .npmrc
          npm run install-attest
          npm install polymer-cli
      - name: Lint
        run: npm run lint
      - name: Unit Tests (SauceLabs)
        run: npm run test:polymer:sauce
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn
