name: CI
on:
  push:
     branches: [ master, release/** ]
  pull_request:

jobs:
  test:
    name: Test
    timeout-minutes: 10
    runs-on: [self-hosted, AWS, Linux]
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '12.x'
          registry-url: https://d2lartifacts.jfrog.io/d2lartifacts/api/npm/npm-local
          scope: '@d2l'

      - name: Install dependencies
        run: |
            npm ci
            npm run install-attest
            npm install polymer-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_NPM_RO_TOKEN }}

      - name: Lint
        run: npm run lint
      - name: Unit Tests (SauceLabs)
        run: npm run test:polymer:sauce
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn
